#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh  —  Jelly-Social first-time setup wizard (Mac / Linux)
# Run once after cloning: bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

JELLY_HOME="$HOME/.jelly-social"
KEYS_FILE="$JELLY_HOME/.keys"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}  ╔══════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}  ║         Jelly-Social Setup Wizard                ║${NC}"
  echo -e "${CYAN}  ║   Social Media AI Agent — github.com/jelly-chain ║${NC}"
  echo -e "${CYAN}  ╚══════════════════════════════════════════════════╝${NC}"
  echo ""
}

step() { echo -e "${CYAN}  ▶ $1${NC}"; }
ok()   { echo -e "${GREEN}  ✓ $1${NC}"; }
warn() { echo -e "${YELLOW}  ⚠ $1${NC}"; }
err()  { echo -e "${RED}  ✗ $1${NC}"; }

banner

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
step "Checking Node.js..."
if ! command -v node &>/dev/null; then
  err "Node.js not found. Install from https://nodejs.org (v18 or later)"
  exit 1
fi
ok "Node.js $(node --version) found"

# ── 2. Check npm ─────────────────────────────────────────────────────────────
step "Checking npm..."
if ! command -v npm &>/dev/null; then
  err "npm not found. Re-install Node.js from https://nodejs.org"
  exit 1
fi
ok "npm $(npm --version) found"

# ── 3. Install Claude Code ───────────────────────────────────────────────────
step "Installing Claude Code CLI..."
if command -v claude &>/dev/null; then
  ok "Claude Code already installed"
else
  npm install -g @anthropic-ai/claude-code
  ok "Claude Code installed"
fi

# ── 4. Create .env ──────────────────────────────────────────────────────────
step "Setting up .env..."
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  cat > "$SCRIPT_DIR/.env" << 'EOF'
# Jelly-Social — API keys for Claude Code
# Add ONE of the following (Anthropic recommended for best quality):

# ANTHROPIC_API_KEY=sk-ant-...
# OPENROUTER_API_KEY=sk-or-...
EOF
  warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
else
  ok ".env already exists"
fi

# ── 5. Create keys directory ─────────────────────────────────────────────────
step "Creating keys directory..."
mkdir -p "$JELLY_HOME"
chmod 700 "$JELLY_HOME"
ok "Keys directory: $JELLY_HOME"

# ── 6. Optional: Social platform API keys ─────────────────────────────────
step "Optional: Social platform API keys (press Enter to skip any)"
echo ""

echo "  X (Twitter) — get keys at developer.x.com"
read -r -p "  TWITTER_API_KEY (Enter to skip): " TW_KEY
read -r -p "  TWITTER_API_SECRET (Enter to skip): " TW_SECRET
read -r -p "  TWITTER_BEARER_TOKEN (Enter to skip): " TW_BEARER
read -r -p "  TWITTER_ACCESS_TOKEN (Enter to skip): " TW_AT
read -r -p "  TWITTER_ACCESS_SECRET (Enter to skip): " TW_AS

echo ""
echo "  Reddit — create a script app at reddit.com/prefs/apps"
read -r -p "  REDDIT_CLIENT_ID (Enter to skip): " RD_ID
read -r -p "  REDDIT_CLIENT_SECRET (Enter to skip): " RD_SECRET
read -r -p "  REDDIT_USERNAME (Enter to skip): " RD_USER
read -r -p "  REDDIT_PASSWORD (Enter to skip): " RD_PASS

echo ""
echo "  Discord — get bot token at discord.com/developers/applications"
read -r -p "  DISCORD_BOT_TOKEN (Enter to skip): " DC_TOKEN
read -r -p "  DISCORD_WEBHOOK_URL (Enter to skip): " DC_WEBHOOK

echo ""
echo "  Telegram — get bot token from @BotFather on Telegram"
read -r -p "  TELEGRAM_BOT_TOKEN (Enter to skip): " TG_TOKEN
read -r -p "  TELEGRAM_CHAT_ID (Enter to skip): " TG_CHAT

echo ""
echo "  LinkedIn — run OAuth2 flow at linkedin.com/developers/apps"
read -r -p "  LINKEDIN_CLIENT_ID (Enter to skip): " LI_ID
read -r -p "  LINKEDIN_CLIENT_SECRET (Enter to skip): " LI_SECRET
read -r -p "  LINKEDIN_ACCESS_TOKEN (Enter to skip): " LI_TOKEN

echo ""
echo "  TikTok — register app at developers.tiktok.com"
read -r -p "  TIKTOK_CLIENT_KEY (Enter to skip): " TK_KEY
read -r -p "  TIKTOK_CLIENT_SECRET (Enter to skip): " TK_SECRET
read -r -p "  TIKTOK_ACCESS_TOKEN (Enter to skip): " TK_TOKEN

cat > "$KEYS_FILE" << KEYSEOF
# Jelly-Social keys — DO NOT commit this file
# Generated by setup.sh on $(date)

TWITTER_API_KEY=${TW_KEY:-}
TWITTER_API_SECRET=${TW_SECRET:-}
TWITTER_BEARER_TOKEN=${TW_BEARER:-}
TWITTER_ACCESS_TOKEN=${TW_AT:-}
TWITTER_ACCESS_SECRET=${TW_AS:-}

REDDIT_CLIENT_ID=${RD_ID:-}
REDDIT_CLIENT_SECRET=${RD_SECRET:-}
REDDIT_USERNAME=${RD_USER:-}
REDDIT_PASSWORD=${RD_PASS:-}

DISCORD_BOT_TOKEN=${DC_TOKEN:-}
DISCORD_WEBHOOK_URL=${DC_WEBHOOK:-}

TELEGRAM_BOT_TOKEN=${TG_TOKEN:-}
TELEGRAM_CHAT_ID=${TG_CHAT:-}

LINKEDIN_CLIENT_ID=${LI_ID:-}
LINKEDIN_CLIENT_SECRET=${LI_SECRET:-}
LINKEDIN_ACCESS_TOKEN=${LI_TOKEN:-}
LINKEDIN_REDIRECT_URI=http://localhost:3000/callback

TIKTOK_CLIENT_KEY=${TK_KEY:-}
TIKTOK_CLIENT_SECRET=${TK_SECRET:-}
TIKTOK_ACCESS_TOKEN=${TK_TOKEN:-}
KEYSEOF
chmod 600 "$KEYS_FILE"
ok "Keys saved to $KEYS_FILE"

# ── 7. Install skills ────────────────────────────────────────────────────────
SKILLS_REPO_DIR="$PARENT_DIR/jelly-social-skills"
if [[ -d "$SKILLS_REPO_DIR" ]]; then
  step "Installing all skills..."
  bash "$SKILLS_REPO_DIR/install-all.sh"
  ok "All skills installed"
else
  warn "jelly-social-skills not found at $SKILLS_REPO_DIR"
  warn "Clone it first: git clone https://github.com/jelly-chain/jelly-social-skills"
fi

# ── 8. Install agent templates ───────────────────────────────────────────────
AGENTS_REPO_DIR="$PARENT_DIR/jelly-social-agents"
if [[ -d "$AGENTS_REPO_DIR" ]]; then
  step "Installing all agent templates..."
  bash "$AGENTS_REPO_DIR/install-all.sh"
  ok "All agent templates installed"
else
  warn "jelly-social-agents not found at $AGENTS_REPO_DIR"
  warn "Clone it first: git clone https://github.com/jelly-chain/jelly-social-agents"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "    1. Add your API key to: $SCRIPT_DIR/.env"
echo "       (ANTHROPIC_API_KEY or OPENROUTER_API_KEY)"
echo "    2. Add your social platform keys to: $KEYS_FILE"
echo "    3. Start the agent:"
echo "       bash jelly-social.sh"
echo ""
echo "  Available agents:"
echo "    /agent tweet-scheduler"
echo "    /agent reddit-researcher"
echo "    /agent discord-moderator"
echo "    /agent telegram-broadcaster"
echo "    /agent linkedin-poster"
echo "    /agent viral-hunter"
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo ""
