# ─────────────────────────────────────────────────────────────────────────────
# setup.ps1  —  Jelly-Social first-time setup wizard (Windows PowerShell)
# Run once after cloning: .\setup.ps1
# ─────────────────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"

$JellyHome = Join-Path $env:USERPROFILE ".jelly-social"
$KeysFile  = Join-Path $JellyHome ".keys"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir

function Step($msg)  { Write-Host "  > $msg" -ForegroundColor Cyan }
function Ok($msg)    { Write-Host "  + $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Err($msg)   { Write-Host "  X $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║         Jelly-Social Setup Wizard                ║" -ForegroundColor Cyan
Write-Host "  ║   Social Media AI Agent — github.com/jelly-chain ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
Step "Checking Node.js..."
try { $nodeVer = node --version; Ok "Node.js $nodeVer found" }
catch { Err "Node.js not found. Install from https://nodejs.org (v18+)"; exit 1 }

# ── 2. Check npm ─────────────────────────────────────────────────────────────
Step "Checking npm..."
try { $npmVer = npm --version; Ok "npm $npmVer found" }
catch { Err "npm not found. Re-install Node.js"; exit 1 }

# ── 3. Install Claude Code ───────────────────────────────────────────────────
Step "Installing Claude Code CLI..."
if (Get-Command claude -ErrorAction SilentlyContinue) {
    Ok "Claude Code already installed"
} else {
    npm install -g @anthropic-ai/claude-code
    Ok "Claude Code installed"
}

# ── 4. Setup .env ────────────────────────────────────────────────────────────
Step "Setting up .env..."
$envPath = Join-Path $ScriptDir ".env"
if (-not (Test-Path $envPath)) {
    Set-Content $envPath "# ANTHROPIC_API_KEY=sk-ant-...`n# OPENROUTER_API_KEY=sk-or-..."
    Warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
} else {
    Ok ".env already exists"
}

# ── 5. Create keys directory ─────────────────────────────────────────────────
Step "Creating keys directory..."
New-Item -ItemType Directory -Force -Path $JellyHome | Out-Null
Ok "Keys directory: $JellyHome"

# ── 6. Optional: Social platform API keys ────────────────────────────────────
Step "Optional: Social platform API keys (press Enter to skip any)"
Write-Host ""

Write-Host "  X (Twitter) — create app at developer.x.com"
$TwKey     = Read-Host "  TWITTER_API_KEY (Enter to skip)"
$TwSecret  = Read-Host "  TWITTER_API_SECRET (Enter to skip)"
$TwBearer  = Read-Host "  TWITTER_BEARER_TOKEN (Enter to skip)"
$TwAt      = Read-Host "  TWITTER_ACCESS_TOKEN (Enter to skip)"
$TwAs      = Read-Host "  TWITTER_ACCESS_SECRET (Enter to skip)"

Write-Host ""
Write-Host "  Reddit — create script app at reddit.com/prefs/apps"
$RdId      = Read-Host "  REDDIT_CLIENT_ID (Enter to skip)"
$RdSecret  = Read-Host "  REDDIT_CLIENT_SECRET (Enter to skip)"
$RdUser    = Read-Host "  REDDIT_USERNAME (Enter to skip)"
$RdPass    = Read-Host "  REDDIT_PASSWORD (Enter to skip)"

Write-Host ""
Write-Host "  Discord — get bot token at discord.com/developers/applications"
$DcToken   = Read-Host "  DISCORD_BOT_TOKEN (Enter to skip)"
$DcWebhook = Read-Host "  DISCORD_WEBHOOK_URL (Enter to skip)"
$DcAppId   = Read-Host "  DISCORD_APP_ID (Enter to skip)"
$DcGuild   = Read-Host "  DISCORD_GUILD_ID (Enter to skip)"

Write-Host ""
Write-Host "  Telegram — get bot token from @BotFather on Telegram"
$TgToken   = Read-Host "  TELEGRAM_BOT_TOKEN (Enter to skip)"
$TgChat    = Read-Host "  TELEGRAM_CHAT_ID (Enter to skip)"

Write-Host ""
Write-Host "  LinkedIn — run OAuth2 flow at linkedin.com/developers/apps"
$LiId      = Read-Host "  LINKEDIN_CLIENT_ID (Enter to skip)"
$LiSecret  = Read-Host "  LINKEDIN_CLIENT_SECRET (Enter to skip)"
$LiToken   = Read-Host "  LINKEDIN_ACCESS_TOKEN (Enter to skip)"

Write-Host ""
Write-Host "  TikTok — register app at developers.tiktok.com"
$TkKey     = Read-Host "  TIKTOK_CLIENT_KEY (Enter to skip)"
$TkSecret  = Read-Host "  TIKTOK_CLIENT_SECRET (Enter to skip)"
$TkToken   = Read-Host "  TIKTOK_ACCESS_TOKEN (Enter to skip)"

$keysContent = @"
# Jelly-Social keys - DO NOT commit this file
# Generated by setup.ps1

TWITTER_API_KEY=$TwKey
TWITTER_API_SECRET=$TwSecret
TWITTER_BEARER_TOKEN=$TwBearer
TWITTER_ACCESS_TOKEN=$TwAt
TWITTER_ACCESS_SECRET=$TwAs

REDDIT_CLIENT_ID=$RdId
REDDIT_CLIENT_SECRET=$RdSecret
REDDIT_USERNAME=$RdUser
REDDIT_PASSWORD=$RdPass

DISCORD_BOT_TOKEN=$DcToken
DISCORD_WEBHOOK_URL=$DcWebhook
DISCORD_APP_ID=$DcAppId
DISCORD_GUILD_ID=$DcGuild

TELEGRAM_BOT_TOKEN=$TgToken
TELEGRAM_CHAT_ID=$TgChat

LINKEDIN_CLIENT_ID=$LiId
LINKEDIN_CLIENT_SECRET=$LiSecret
LINKEDIN_ACCESS_TOKEN=$LiToken
LINKEDIN_REDIRECT_URI=http://localhost:3000/callback

TIKTOK_CLIENT_KEY=$TkKey
TIKTOK_CLIENT_SECRET=$TkSecret
TIKTOK_ACCESS_TOKEN=$TkToken
"@

Set-Content -Path $KeysFile -Value $keysContent
Ok "Keys saved to $KeysFile"

# ── 7. Install skills ────────────────────────────────────────────────────────
$skillsDir = Join-Path $ParentDir "jelly-social-skills"
if (Test-Path $skillsDir) {
    Step "Installing all skills..."
    & (Join-Path $skillsDir "install-all.ps1")
    Ok "All skills installed"
} else {
    Warn "jelly-social-skills not found at $skillsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-social-skills"
}

# ── 8. Install agent templates ───────────────────────────────────────────────
$agentsDir = Join-Path $ParentDir "jelly-social-agents"
if (Test-Path $agentsDir) {
    Step "Installing all agent templates..."
    & (Join-Path $agentsDir "install-all.ps1")
    Ok "All agent templates installed"
} else {
    Warn "jelly-social-agents not found at $agentsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-social-agents"
}

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Add your API key to: $envPath"
Write-Host "       (ANTHROPIC_API_KEY or OPENROUTER_API_KEY)"
Write-Host "    2. Update social platform keys in: $KeysFile"
Write-Host "    3. Start: .\jelly-social.ps1"
Write-Host ""
Write-Host "  Available agents:"
Write-Host "    /agent tweet-scheduler"
Write-Host "    /agent reddit-researcher"
Write-Host "    /agent discord-moderator"
Write-Host "    /agent telegram-broadcaster"
Write-Host "    /agent linkedin-poster"
Write-Host "    /agent viral-hunter"
Write-Host ""
