#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh  —  Jelly-Forex first-time setup wizard (Mac / Linux)
# Run once after cloning: bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

JELLY_HOME="$HOME/.jelly-forex"
KEYS_FILE="$JELLY_HOME/.keys"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}  ╔══════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}  ║         Jelly-Forex Setup Wizard                 ║${NC}"
  echo -e "${CYAN}  ║   Traditional Finance AI Agent                   ║${NC}"
  echo -e "${CYAN}  ╚══════════════════════════════════════════════════╝${NC}"
  echo ""
}

step() { echo -e "${CYAN}  ▶ $1${NC}"; }
ok()   { echo -e "${GREEN}  ✓ $1${NC}"; }
warn() { echo -e "${YELLOW}  ⚠ $1${NC}"; }
err()  { echo -e "${RED}  ✗ $1${NC}"; }

banner

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
step "Checking Node.js..."
if ! command -v node &>/dev/null; then
  err "Node.js not found."
  echo "  Install from https://nodejs.org (v18 or later recommended)"
  exit 1
fi
ok "Node.js $(node --version) found"

# ── 2. Check npm ─────────────────────────────────────────────────────────────
step "Checking npm..."
if ! command -v npm &>/dev/null; then
  err "npm not found. Re-install Node.js from https://nodejs.org"
  exit 1
fi
ok "npm $(npm --version) found"

# ── 3. Check git ─────────────────────────────────────────────────────────────
step "Checking git..."
if ! command -v git &>/dev/null; then
  err "git not found. Install from https://git-scm.com"
  exit 1
fi
ok "git $(git --version | awk '{print $3}') found"

# ── 4. Check Python 3 (for yfinance-skill) ───────────────────────────────────
step "Checking Python 3 (for yfinance-skill)..."
if command -v python3 &>/dev/null; then
  ok "Python3 $(python3 --version | awk '{print $2}') found"
  if command -v pip3 &>/dev/null; then
    ok "pip3 found"
  else
    warn "pip3 not found — install it to use yfinance-skill"
  fi
else
  warn "Python 3 not found — yfinance-skill requires Python 3. Install from https://python.org"
fi

# ── 5. Install Claude Code ───────────────────────────────────────────────────
step "Installing Claude Code CLI..."
if command -v claude &>/dev/null; then
  ok "Claude Code already installed ($(claude --version 2>/dev/null | head -1 || echo 'installed'))"
else
  npm install -g @anthropic-ai/claude-code
  ok "Claude Code installed"
fi

# ── 6. Create keys directory ─────────────────────────────────────────────────
step "Creating keys directory..."
mkdir -p "$JELLY_HOME"
chmod 700 "$JELLY_HOME"
ok "Keys directory: $JELLY_HOME"

# ── 7. Collect API keys ───────────────────────────────────────────────────────
step "Setting up API keys..."
echo ""
echo "  Press Enter to skip any key you don't have yet."
echo "  All keys are stored at $KEYS_FILE (chmod 600)"
echo ""

echo "  ALPACA (stock trading) — get at: https://alpaca.markets → Paper Trading"
read -r -p "  ALPACA_API_KEY (Enter to skip): " ALPACA_KEY
read -r -p "  ALPACA_API_SECRET (Enter to skip): " ALPACA_SECRET

echo ""
echo "  OANDA (forex trading) — get at: https://oanda.com → My Account → API Access"
read -r -p "  OANDA_API_TOKEN (Enter to skip): " OANDA_TOKEN
read -r -p "  OANDA_ACCOUNT_ID (Enter to skip, format 101-004-XXXXXXX-001): " OANDA_ACCOUNT

echo ""
echo "  POLYGON.IO (options + market data) — get at: https://polygon.io"
read -r -p "  POLYGON_API_KEY (Enter to skip): " POLYGON_KEY

echo ""
echo "  ALPHA VANTAGE (fundamentals) — free key at: https://alphavantage.co"
read -r -p "  ALPHA_VANTAGE_API_KEY (Enter to skip): " AV_KEY

echo ""
echo "  SEC EDGAR (filing research) — no key needed, just your name + email"
read -r -p "  SEC_USER_AGENT (format: 'YourName email@example.com'): " SEC_AGENT

# Write .keys file
cat > "$KEYS_FILE" << KEYSEOF
# Jelly-Forex keys — DO NOT commit this file
# Generated by setup.sh on $(date)

# Alpaca — stock/ETF trading (paper and live)
ALPACA_API_KEY=${ALPACA_KEY:-}
ALPACA_API_SECRET=${ALPACA_SECRET:-}
ALPACA_PAPER=true

# OANDA — forex/CFD trading (practice and live)
OANDA_API_TOKEN=${OANDA_TOKEN:-}
OANDA_ACCOUNT_ID=${OANDA_ACCOUNT:-}
OANDA_PRACTICE=true

# Polygon.io — options chains, market data
POLYGON_API_KEY=${POLYGON_KEY:-}

# Alpha Vantage — fundamentals, earnings, indicators
ALPHA_VANTAGE_API_KEY=${AV_KEY:-}

# SEC EDGAR — filing research (email string, no actual API key)
SEC_USER_AGENT=${SEC_AGENT:-JellyForex research@example.com}
KEYSEOF
chmod 600 "$KEYS_FILE"
ok "Keys saved to $KEYS_FILE"

# ── 8. Clone & install skills ─────────────────────────────────────────────────
step "Cloning jelly-forex-skills..."
SKILLS_REPO_DIR="$PARENT_DIR/jelly-forex-skills"
if [[ -d "$SKILLS_REPO_DIR/.git" ]]; then
  ok "jelly-forex-skills already cloned — pulling latest..."
  git -C "$SKILLS_REPO_DIR" pull --quiet || warn "git pull failed; continuing with existing version"
elif [[ -d "$SKILLS_REPO_DIR" ]]; then
  ok "jelly-forex-skills directory found (not a git repo — using as-is)"
else
  git clone https://github.com/jelly-chain/jelly-forex-skills.git "$SKILLS_REPO_DIR"
  ok "jelly-forex-skills cloned"
fi

step "Installing all skills..."
bash "$SKILLS_REPO_DIR/install-all.sh"
ok "All skills installed"

# ── 9. Clone & install agents ─────────────────────────────────────────────────
step "Cloning jelly-forex-agents..."
AGENTS_REPO_DIR="$PARENT_DIR/jelly-forex-agents"
if [[ -d "$AGENTS_REPO_DIR/.git" ]]; then
  ok "jelly-forex-agents already cloned — pulling latest..."
  git -C "$AGENTS_REPO_DIR" pull --quiet || warn "git pull failed; continuing with existing version"
elif [[ -d "$AGENTS_REPO_DIR" ]]; then
  ok "jelly-forex-agents directory found (not a git repo — using as-is)"
else
  git clone https://github.com/jelly-chain/jelly-forex-agents.git "$AGENTS_REPO_DIR"
  ok "jelly-forex-agents cloned"
fi

step "Installing all agent templates..."
bash "$AGENTS_REPO_DIR/install-all.sh"
ok "All agent templates installed"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo ""
echo "  Keys stored at:  $KEYS_FILE"
echo ""
echo "  Next steps:"
if [[ -z "${ALPACA_KEY:-}" ]]; then
  echo "    ⚠  Add ALPACA_API_KEY to $KEYS_FILE (paper trading account)"
else
  echo "    ✓  Alpaca key set"
fi
if [[ -z "${OANDA_TOKEN:-}" ]]; then
  echo "    ⚠  Add OANDA_API_TOKEN + OANDA_ACCOUNT_ID to $KEYS_FILE"
else
  echo "    ✓  OANDA key set"
fi
echo ""
echo "  Start the agent:"
echo "    bash jelly-forex.sh"
echo ""
echo "  See STRATEGIES.md for trading playbooks."
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo ""
