# setup.ps1 — Jelly-Forex first-time setup wizard (Windows)
# Run once after cloning: .\setup.ps1

$JellyHome    = "$env:USERPROFILE\.jelly-forex"
$KeysFile     = "$JellyHome\.keys"
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir    = Split-Path -Parent $ScriptDir

function Write-Banner {
  Write-Host ""
  Write-Host "  ╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
  Write-Host "  ║         Jelly-Forex Setup Wizard                 ║" -ForegroundColor Cyan
  Write-Host "  ║   Traditional Finance AI Agent                   ║" -ForegroundColor Cyan
  Write-Host "  ╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
  Write-Host ""
}

function Step($msg) { Write-Host "  > $msg" -ForegroundColor Cyan }
function Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "  [!] $msg"  -ForegroundColor Yellow }
function Err($msg)  { Write-Host "  [X] $msg"  -ForegroundColor Red }

Write-Banner

# Check Node.js
Step "Checking Node.js..."
try { $nv = (node --version 2>&1); Ok "Node.js $nv found" } catch { Err "Node.js not found — install from https://nodejs.org"; exit 1 }

# Check npm
Step "Checking npm..."
try { $npmv = (npm --version 2>&1); Ok "npm $npmv found" } catch { Err "npm not found — reinstall Node.js"; exit 1 }

# Check git
Step "Checking git..."
try { $gitv = (git --version 2>&1); Ok "$gitv" } catch { Err "git not found — install from https://git-scm.com"; exit 1 }

# Check Python 3
Step "Checking Python 3 (for yfinance-skill)..."
try { $pyv = (python --version 2>&1); Ok "$pyv" } catch { Warn "Python 3 not found — yfinance-skill requires Python. Install from https://python.org" }

# Install Claude Code
Step "Installing Claude Code CLI..."
$hasC = (Get-Command claude -ErrorAction SilentlyContinue)
if ($hasC) { Ok "Claude Code already installed" }
else { npm install -g @anthropic-ai/claude-code; Ok "Claude Code installed" }

# Create keys directory
Step "Creating keys directory..."
New-Item -ItemType Directory -Force -Path $JellyHome | Out-Null
Ok "Keys directory: $JellyHome"

# Collect keys
Step "Setting up API keys..."
Write-Host ""
Write-Host "  Press Enter to skip any key you don't have yet." -ForegroundColor Yellow
Write-Host ""

Write-Host "  ALPACA — https://alpaca.markets -> Paper Trading"
$alpacaKey    = Read-Host "  ALPACA_API_KEY (Enter to skip)"
$alpacaSecret = Read-Host "  ALPACA_API_SECRET (Enter to skip)"

Write-Host ""
Write-Host "  OANDA — https://oanda.com -> My Account -> API Access"
$oandaToken   = Read-Host "  OANDA_API_TOKEN (Enter to skip)"
$oandaAccount = Read-Host "  OANDA_ACCOUNT_ID (Enter to skip)"

Write-Host ""
Write-Host "  POLYGON.IO — https://polygon.io"
$polygonKey   = Read-Host "  POLYGON_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  ALPHA VANTAGE — https://alphavantage.co (free key)"
$avKey        = Read-Host "  ALPHA_VANTAGE_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  SEC EDGAR — no key, just name + email"
$secAgent     = Read-Host "  SEC_USER_AGENT (e.g. 'YourName email@example.com')"
if (-not $secAgent) { $secAgent = "JellyForex research@example.com" }

$keysContent = @"
# Jelly-Forex keys -- DO NOT commit this file
# Generated by setup.ps1 on $(Get-Date)

ALPACA_API_KEY=$alpacaKey
ALPACA_API_SECRET=$alpacaSecret
ALPACA_PAPER=true

OANDA_API_TOKEN=$oandaToken
OANDA_ACCOUNT_ID=$oandaAccount
OANDA_PRACTICE=true

POLYGON_API_KEY=$polygonKey

ALPHA_VANTAGE_API_KEY=$avKey

SEC_USER_AGENT=$secAgent
"@

Set-Content -Path $KeysFile -Value $keysContent
Ok "Keys saved to $KeysFile"

# Clone and install skills
Step "Cloning jelly-forex-skills..."
$skillsDir = Join-Path $ParentDir "jelly-forex-skills"
if (Test-Path (Join-Path $skillsDir ".git")) {
  Ok "jelly-forex-skills already cloned — pulling..."
  git -C $skillsDir pull --quiet 2>$null
} elseif (Test-Path $skillsDir) {
  Ok "jelly-forex-skills directory found (not git — using as-is)"
} else {
  git clone https://github.com/jelly-chain/jelly-forex-skills.git $skillsDir
  Ok "jelly-forex-skills cloned"
}
& (Join-Path $skillsDir "install-all.ps1")

# Clone and install agents
Step "Cloning jelly-forex-agents..."
$agentsDir = Join-Path $ParentDir "jelly-forex-agents"
if (Test-Path (Join-Path $agentsDir ".git")) {
  Ok "jelly-forex-agents already cloned — pulling..."
  git -C $agentsDir pull --quiet 2>$null
} elseif (Test-Path $agentsDir) {
  Ok "jelly-forex-agents directory found (not git — using as-is)"
} else {
  git clone https://github.com/jelly-chain/jelly-forex-agents.git $agentsDir
  Ok "jelly-forex-agents cloned"
}
& (Join-Path $agentsDir "install-all.ps1")

# Summary
Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host "  Keys stored at: $KeysFile"
Write-Host ""
Write-Host "  Start the agent:"
Write-Host "    .\jelly-forex.ps1"
Write-Host ""
