#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh  —  Jelly-Research first-time setup wizard (Mac / Linux)
# Run once after cloning: bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

JELLY_HOME="$HOME/.jelly-research"
KEYS_FILE="$JELLY_HOME/.keys"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}  ╔══════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}  ║         Jelly-Research Setup Wizard              ║${NC}"
  echo -e "${CYAN}  ║   Research AI Agent — github.com/jelly-chain     ║${NC}"
  echo -e "${CYAN}  ╚══════════════════════════════════════════════════╝${NC}"
  echo ""
}

step() { echo -e "${CYAN}  ▶ $1${NC}"; }
ok()   { echo -e "${GREEN}  ✓ $1${NC}"; }
warn() { echo -e "${YELLOW}  ⚠ $1${NC}"; }
err()  { echo -e "${RED}  ✗ $1${NC}"; }

banner

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
step "Checking Node.js..."
if ! command -v node &>/dev/null; then
  err "Node.js not found. Install from https://nodejs.org (v18 or later)"
  exit 1
fi
ok "Node.js $(node --version) found"

# ── 2. Check npm ─────────────────────────────────────────────────────────────
step "Checking npm..."
if ! command -v npm &>/dev/null; then
  err "npm not found. Re-install Node.js from https://nodejs.org"
  exit 1
fi
ok "npm $(npm --version) found"

# ── 3. Install Claude Code ───────────────────────────────────────────────────
step "Installing Claude Code CLI..."
if command -v claude &>/dev/null; then
  ok "Claude Code already installed"
else
  npm install -g @anthropic-ai/claude-code
  ok "Claude Code installed"
fi

# ── 4. Create .env ──────────────────────────────────────────────────────────
step "Setting up .env..."
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  cat > "$SCRIPT_DIR/.env" << 'EOF'
# Jelly-Research — Claude API key
# Add ONE of the following:

# ANTHROPIC_API_KEY=sk-ant-...
# OPENROUTER_API_KEY=sk-or-...
EOF
  warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
else
  ok ".env already exists"
fi

# ── 5. Create keys directory ─────────────────────────────────────────────────
step "Creating keys directory..."
mkdir -p "$JELLY_HOME"
chmod 700 "$JELLY_HOME"
ok "Keys directory: $JELLY_HOME"

# ── 6. Optional: Research API keys ──────────────────────────────────────────
step "Optional: Research API keys (press Enter to skip any)"
echo ""

echo "  Perplexity AI — get key at perplexity.ai"
read -r -p "  PERPLEXITY_API_KEY (Enter to skip): " PP_KEY

echo ""
echo "  Exa (neural search) — get key at exa.ai"
read -r -p "  EXA_API_KEY (Enter to skip): " EXA_KEY

echo ""
echo "  NewsAPI — get key at newsapi.org"
read -r -p "  NEWSAPI_KEY (Enter to skip): " NEWS_KEY

echo ""
echo "  SerpAPI — get key at serpapi.com"
read -r -p "  SERPAPI_KEY (Enter to skip): " SERP_KEY

echo ""
echo "  Tavily — get key at app.tavily.com"
read -r -p "  TAVILY_API_KEY (Enter to skip): " TAVILY_KEY

echo ""
echo "  Firecrawl — get key at firecrawl.dev"
read -r -p "  FIRECRAWL_API_KEY (Enter to skip): " FC_KEY

cat > "$KEYS_FILE" << KEYSEOF
# Jelly-Research keys — DO NOT commit this file
# Generated by setup.sh on $(date)

PERPLEXITY_API_KEY=${PP_KEY:-}
EXA_API_KEY=${EXA_KEY:-}
NEWSAPI_KEY=${NEWS_KEY:-}
SERPAPI_KEY=${SERP_KEY:-}
TAVILY_API_KEY=${TAVILY_KEY:-}
FIRECRAWL_API_KEY=${FC_KEY:-}
KEYSEOF
chmod 600 "$KEYS_FILE"
ok "Keys saved to $KEYS_FILE"

# ── 7. Install skills ────────────────────────────────────────────────────────
SKILLS_REPO_DIR="$PARENT_DIR/jelly-research-skills"
if [[ -d "$SKILLS_REPO_DIR" ]]; then
  step "Installing all skills..."
  bash "$SKILLS_REPO_DIR/install-all.sh"
  ok "All skills installed"
else
  warn "jelly-research-skills not found at $SKILLS_REPO_DIR"
  warn "Clone it: git clone https://github.com/jelly-chain/jelly-research-skills"
fi

# ── 8. Install agent templates ───────────────────────────────────────────────
AGENTS_REPO_DIR="$PARENT_DIR/jelly-research-agents"
if [[ -d "$AGENTS_REPO_DIR" ]]; then
  step "Installing all agent templates..."
  bash "$AGENTS_REPO_DIR/install-all.sh"
  ok "All agent templates installed"
else
  warn "jelly-research-agents not found at $AGENTS_REPO_DIR"
  warn "Clone it: git clone https://github.com/jelly-chain/jelly-research-agents"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "    1. Add your API key to: $SCRIPT_DIR/.env"
echo "       (ANTHROPIC_API_KEY or OPENROUTER_API_KEY)"
echo "    2. Add research API keys to: $KEYS_FILE"
echo "    3. Start the agent:"
echo "       bash jelly-research.sh"
echo ""
echo "  Available agents:"
echo "    /agent deep-researcher"
echo "    /agent news-monitor"
echo "    /agent fact-checker"
echo "    /agent serp-analyst"
echo "    /agent competitive-intel"
echo "    /agent web-scraper"
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo ""
