# ─────────────────────────────────────────────────────────────────────────────
# setup.ps1  —  Jelly-Research first-time setup wizard (Windows PowerShell)
# Run once after cloning: .\setup.ps1
# ─────────────────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"

$JellyHome = Join-Path $env:USERPROFILE ".jelly-research"
$KeysFile  = Join-Path $JellyHome ".keys"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir

function Step($msg)  { Write-Host "  > $msg" -ForegroundColor Cyan }
function Ok($msg)    { Write-Host "  + $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Err($msg)   { Write-Host "  X $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║         Jelly-Research Setup Wizard              ║" -ForegroundColor Cyan
Write-Host "  ║   Research AI Agent — github.com/jelly-chain     ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
Step "Checking Node.js..."
try { $nodeVer = node --version; Ok "Node.js $nodeVer found" }
catch { Err "Node.js not found. Install from https://nodejs.org (v18+)"; exit 1 }

# ── 2. Check npm ─────────────────────────────────────────────────────────────
Step "Checking npm..."
try { $npmVer = npm --version; Ok "npm $npmVer found" }
catch { Err "npm not found. Re-install Node.js"; exit 1 }

# ── 3. Install Claude Code ───────────────────────────────────────────────────
Step "Installing Claude Code CLI..."
if (Get-Command claude -ErrorAction SilentlyContinue) {
    Ok "Claude Code already installed"
} else {
    npm install -g @anthropic-ai/claude-code
    Ok "Claude Code installed"
}

# ── 4. Setup .env ────────────────────────────────────────────────────────────
Step "Setting up .env..."
$envPath = Join-Path $ScriptDir ".env"
if (-not (Test-Path $envPath)) {
    Set-Content $envPath "# ANTHROPIC_API_KEY=sk-ant-...`n# OPENROUTER_API_KEY=sk-or-..."
    Warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
} else {
    Ok ".env already exists"
}

# ── 5. Create keys directory ─────────────────────────────────────────────────
Step "Creating keys directory..."
New-Item -ItemType Directory -Force -Path $JellyHome | Out-Null
Ok "Keys directory: $JellyHome"

# ── 6. Optional: Research API keys ───────────────────────────────────────────
Step "Optional: Research API keys (press Enter to skip any)"
Write-Host ""

Write-Host "  Perplexity AI — get key at perplexity.ai"
$PpKey = Read-Host "  PERPLEXITY_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Exa (neural search) — get key at exa.ai"
$ExaKey = Read-Host "  EXA_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  NewsAPI — get key at newsapi.org"
$NewsKey = Read-Host "  NEWSAPI_KEY (Enter to skip)"

Write-Host ""
Write-Host "  SerpAPI — get key at serpapi.com"
$SerpKey = Read-Host "  SERPAPI_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Tavily — get key at app.tavily.com"
$TavilyKey = Read-Host "  TAVILY_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Firecrawl — get key at firecrawl.dev"
$FcKey = Read-Host "  FIRECRAWL_API_KEY (Enter to skip)"

$keysContent = @"
# Jelly-Research keys - DO NOT commit this file
# Generated by setup.ps1

PERPLEXITY_API_KEY=$PpKey
EXA_API_KEY=$ExaKey
NEWSAPI_KEY=$NewsKey
SERPAPI_KEY=$SerpKey
TAVILY_API_KEY=$TavilyKey
FIRECRAWL_API_KEY=$FcKey
"@

Set-Content -Path $KeysFile -Value $keysContent
Ok "Keys saved to $KeysFile"

# ── 7. Install skills ────────────────────────────────────────────────────────
$skillsDir = Join-Path $ParentDir "jelly-research-skills"
if (Test-Path $skillsDir) {
    Step "Installing all skills..."
    & (Join-Path $skillsDir "install-all.ps1")
    Ok "All skills installed"
} else {
    Warn "jelly-research-skills not found at $skillsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-research-skills"
}

# ── 8. Install agent templates ───────────────────────────────────────────────
$agentsDir = Join-Path $ParentDir "jelly-research-agents"
if (Test-Path $agentsDir) {
    Step "Installing all agent templates..."
    & (Join-Path $agentsDir "install-all.ps1")
    Ok "All agent templates installed"
} else {
    Warn "jelly-research-agents not found at $agentsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-research-agents"
}

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Add your API key to: $envPath"
Write-Host "       (ANTHROPIC_API_KEY or OPENROUTER_API_KEY)"
Write-Host "    2. Update research API keys in: $KeysFile"
Write-Host "    3. Start: .\jelly-research.ps1"
Write-Host ""
Write-Host "  Available agents:"
Write-Host "    /agent deep-researcher"
Write-Host "    /agent news-monitor"
Write-Host "    /agent fact-checker"
Write-Host "    /agent serp-analyst"
Write-Host "    /agent competitive-intel"
Write-Host "    /agent web-scraper"
Write-Host ""
