# ─────────────────────────────────────────────────────────────────────────────
# setup.ps1  —  Jelly-AI first-time setup wizard (Windows PowerShell)
# Run once after cloning: .\setup.ps1
# ─────────────────────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"

$JellyHome = Join-Path $env:USERPROFILE ".jelly-ai"
$KeysFile  = Join-Path $JellyHome ".keys"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir

function Step($msg)  { Write-Host "  > $msg" -ForegroundColor Cyan }
function Ok($msg)    { Write-Host "  + $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Err($msg)   { Write-Host "  X $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║         Jelly-AI Setup Wizard                    ║" -ForegroundColor Cyan
Write-Host "  ║   AI Model Agent — github.com/jelly-chain         ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
Step "Checking Node.js..."
try { $nodeVer = node --version; Ok "Node.js $nodeVer found" }
catch { Err "Node.js not found. Install from https://nodejs.org (v18+)"; exit 1 }

# ── 2. Check npm ─────────────────────────────────────────────────────────────
Step "Checking npm..."
try { $npmVer = npm --version; Ok "npm $npmVer found" }
catch { Err "npm not found. Re-install Node.js"; exit 1 }

# ── 3. Install Claude Code ───────────────────────────────────────────────────
Step "Installing Claude Code CLI..."
if (Get-Command claude -ErrorAction SilentlyContinue) {
    Ok "Claude Code already installed"
} else {
    npm install -g @anthropic-ai/claude-code
    Ok "Claude Code installed"
}

# ── 4. Setup .env ────────────────────────────────────────────────────────────
Step "Setting up .env..."
$envPath = Join-Path $ScriptDir ".env"
if (-not (Test-Path $envPath)) {
    Set-Content $envPath "# ANTHROPIC_API_KEY=sk-ant-...`n# OPENROUTER_API_KEY=sk-or-..."
    Warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
} else {
    Ok ".env already exists"
}

# ── 5. Create keys directory ─────────────────────────────────────────────────
Step "Creating keys directory..."
New-Item -ItemType Directory -Force -Path $JellyHome | Out-Null
Ok "Keys directory: $JellyHome"

# ── 6. Optional: AI API keys ──────────────────────────────────────────────────
Step "Optional: AI API keys (press Enter to skip any)"
Write-Host ""

Write-Host "  OpenAI — get key at platform.openai.com"
$OaiKey = Read-Host "  OPENAI_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Groq — get key at console.groq.com"
$GroqKey = Read-Host "  GROQ_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Replicate — get token at replicate.com"
$RepKey = Read-Host "  REPLICATE_API_TOKEN (Enter to skip)"

Write-Host ""
Write-Host "  ElevenLabs — get key at elevenlabs.io"
$ElKey = Read-Host "  ELEVENLABS_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  Stability AI — get key at platform.stability.ai"
$StabKey = Read-Host "  STABILITY_API_KEY (Enter to skip)"

Write-Host ""
Write-Host "  OpenRouter — get key at openrouter.ai/keys"
$OrKey = Read-Host "  OPENROUTER_API_KEY (Enter to skip)"

$keysContent = @"
# Jelly-AI keys - DO NOT commit this file
# Generated by setup.ps1

OPENAI_API_KEY=$OaiKey
GROQ_API_KEY=$GroqKey
REPLICATE_API_TOKEN=$RepKey
ELEVENLABS_API_KEY=$ElKey
STABILITY_API_KEY=$StabKey
OPENROUTER_API_KEY=$OrKey
"@

Set-Content -Path $KeysFile -Value $keysContent
Ok "Keys saved to $KeysFile"

# ── 7. Install skills ────────────────────────────────────────────────────────
$skillsDir = Join-Path $ParentDir "jelly-ai-skills"
if (Test-Path $skillsDir) {
    Step "Installing all skills..."
    & (Join-Path $skillsDir "install-all.ps1")
    Ok "All skills installed"
} else {
    Warn "jelly-ai-skills not found at $skillsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-ai-skills"
}

# ── 8. Install agent templates ───────────────────────────────────────────────
$agentsDir = Join-Path $ParentDir "jelly-ai-agents"
if (Test-Path $agentsDir) {
    Step "Installing all agent templates..."
    & (Join-Path $agentsDir "install-all.ps1")
    Ok "All agent templates installed"
} else {
    Warn "jelly-ai-agents not found at $agentsDir"
    Warn "Clone it: git clone https://github.com/jelly-chain/jelly-ai-agents"
}

Write-Host ""
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Add your API key to: $envPath"
Write-Host "    2. Update AI API keys in: $KeysFile"
Write-Host "    3. Start: .\jelly-ai.ps1"
Write-Host ""
