#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup.sh  —  Jelly-AI first-time setup wizard (Mac / Linux)
# Run once after cloning: bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

JELLY_HOME="$HOME/.jelly-ai"
KEYS_FILE="$JELLY_HOME/.keys"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}  ╔══════════════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}  ║         Jelly-AI Setup Wizard                    ║${NC}"
  echo -e "${CYAN}  ║   AI Model Agent — github.com/jelly-chain         ║${NC}"
  echo -e "${CYAN}  ╚══════════════════════════════════════════════════╝${NC}"
  echo ""
}

step() { echo -e "${CYAN}  ▶ $1${NC}"; }
ok()   { echo -e "${GREEN}  ✓ $1${NC}"; }
warn() { echo -e "${YELLOW}  ⚠ $1${NC}"; }
err()  { echo -e "${RED}  ✗ $1${NC}"; }

banner

# ── 1. Check Node.js ─────────────────────────────────────────────────────────
step "Checking Node.js..."
if ! command -v node &>/dev/null; then
  err "Node.js not found. Install from https://nodejs.org (v18 or later)"
  exit 1
fi
ok "Node.js $(node --version) found"

# ── 2. Check npm ─────────────────────────────────────────────────────────────
step "Checking npm..."
if ! command -v npm &>/dev/null; then
  err "npm not found. Re-install Node.js from https://nodejs.org"
  exit 1
fi
ok "npm $(npm --version) found"

# ── 3. Install Claude Code ───────────────────────────────────────────────────
step "Installing Claude Code CLI..."
if command -v claude &>/dev/null; then
  ok "Claude Code already installed"
else
  npm install -g @anthropic-ai/claude-code
  ok "Claude Code installed"
fi

# ── 4. Create .env ──────────────────────────────────────────────────────────
step "Setting up .env..."
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  cat > "$SCRIPT_DIR/.env" << 'EOF'
# Jelly-AI — Claude API key (add one of the following)
# ANTHROPIC_API_KEY=sk-ant-...
# OPENROUTER_API_KEY=sk-or-...
EOF
  warn ".env created — add your ANTHROPIC_API_KEY or OPENROUTER_API_KEY before launching"
else
  ok ".env already exists"
fi

# ── 5. Create keys directory ─────────────────────────────────────────────────
step "Creating keys directory..."
mkdir -p "$JELLY_HOME"
chmod 700 "$JELLY_HOME"
ok "Keys directory: $JELLY_HOME"

# ── 6. Optional: AI API keys ─────────────────────────────────────────────────
step "Optional: AI API keys (press Enter to skip any)"
echo ""

echo "  OpenAI — get key at platform.openai.com"
read -r -p "  OPENAI_API_KEY (Enter to skip): " OAI_KEY

echo ""
echo "  Groq — get key at console.groq.com"
read -r -p "  GROQ_API_KEY (Enter to skip): " GROQ_KEY

echo ""
echo "  Replicate — get token at replicate.com"
read -r -p "  REPLICATE_API_TOKEN (Enter to skip): " REP_KEY

echo ""
echo "  ElevenLabs — get key at elevenlabs.io"
read -r -p "  ELEVENLABS_API_KEY (Enter to skip): " EL_KEY

echo ""
echo "  Stability AI — get key at platform.stability.ai"
read -r -p "  STABILITY_API_KEY (Enter to skip): " STAB_KEY

echo ""
echo "  OpenRouter — get key at openrouter.ai/keys"
read -r -p "  OPENROUTER_API_KEY (Enter to skip): " OR_KEY

cat > "$KEYS_FILE" << KEYSEOF
# Jelly-AI keys — DO NOT commit this file
# Generated by setup.sh on $(date)

OPENAI_API_KEY=${OAI_KEY:-}
GROQ_API_KEY=${GROQ_KEY:-}
REPLICATE_API_TOKEN=${REP_KEY:-}
ELEVENLABS_API_KEY=${EL_KEY:-}
STABILITY_API_KEY=${STAB_KEY:-}
OPENROUTER_API_KEY=${OR_KEY:-}
KEYSEOF
chmod 600 "$KEYS_FILE"
ok "Keys saved to $KEYS_FILE"

# ── 7. Install skills ────────────────────────────────────────────────────────
SKILLS_REPO_DIR="$PARENT_DIR/jelly-ai-skills"
if [[ -d "$SKILLS_REPO_DIR" ]]; then
  step "Installing all skills..."
  bash "$SKILLS_REPO_DIR/install-all.sh"
  ok "All skills installed"
else
  warn "jelly-ai-skills not found at $SKILLS_REPO_DIR"
  warn "Clone it: git clone https://github.com/jelly-chain/jelly-ai-skills"
fi

# ── 8. Install agent templates ───────────────────────────────────────────────
AGENTS_REPO_DIR="$PARENT_DIR/jelly-ai-agents"
if [[ -d "$AGENTS_REPO_DIR" ]]; then
  step "Installing all agent templates..."
  bash "$AGENTS_REPO_DIR/install-all.sh"
  ok "All agent templates installed"
else
  warn "jelly-ai-agents not found at $AGENTS_REPO_DIR"
  warn "Clone it: git clone https://github.com/jelly-chain/jelly-ai-agents"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "    1. Add your API key to: $SCRIPT_DIR/.env"
echo "       (ANTHROPIC_API_KEY or OPENROUTER_API_KEY)"
echo "    2. Update AI API keys in: $KEYS_FILE"
echo "    3. Start: bash jelly-ai.sh"
echo ""
echo "  Available agents:"
echo "    /agent gpt-coder"
echo "    /agent fast-summarizer"
echo "    /agent image-generator"
echo "    /agent voice-cloner"
echo "    /agent image-editor"
echo "    /agent model-router"
echo ""
echo -e "${CYAN}  ══════════════════════════════════════════════════${NC}"
echo ""
